/**
 * loadManifest.ts — Runtime loader for kit manifest JSON files.
 *
 * Fetches `/kits/<id>/manifest.json` from the Vite-served `public/` directory.
 * Throws actionable errors on HTTP failure or shape mismatch (including the
 * "assets missing" case with a hint to run `node scripts/build-kits.mjs`).
 */

import type { KitManifest, SamplePad } from "./kit.types";

/**
 * Checks that `x` has the minimal required shape of a `KitManifest`.
 * This is a structural guard — it does not validate every field deeply.
 */
function isKitManifest(x: unknown): x is KitManifest {
  if (typeof x !== "object" || x === null) return false;
  const obj = x as Record<string, unknown>;

  if (typeof obj.id !== "string" || obj.id.trim() === "") return false;
  if (typeof obj.displayName !== "string") return false;
  if (typeof obj.exportName !== "string") return false;
  if (typeof obj.key !== "string") return false;
  if (typeof obj.bpm !== "number") return false;
  if (!Array.isArray(obj.pads)) return false;

  // Validate each pad has the required fields
  for (const pad of obj.pads as unknown[]) {
    if (!isValidSamplePad(pad)) return false;
  }

  return true;
}

/**
 * Validates a single pad entry within a manifest.
 * Checks required numeric and string fields are present and correctly typed.
 */
function isValidSamplePad(x: unknown): x is SamplePad {
  if (typeof x !== "object" || x === null) return false;
  const p = x as Record<string, unknown>;

  return (
    typeof p.globalPadIdx === "number" &&
    typeof p.sampleId === "string" &&
    typeof p.displayName === "string" &&
    typeof p.sampleName === "string" &&
    typeof p.fileName === "string" &&
    (typeof p.url === "string" || p.url === null) &&
    typeof p.coarseTune === "number" &&
    typeof p.fineTune === "number" &&
    typeof p.gainCoefficient === "number" &&
    typeof p.pan === "number"
  );
}

export { isKitManifest };

/**
 * Fetch and validate the manifest for a sample kit.
 *
 * Loads from `/kits/<id>/manifest.json` (Vite serves `public/kits/`).
 *
 * @param id - Kit identifier, e.g. `"london-full"`. Must be URL-safe.
 * @param signal - Optional `AbortSignal` to cancel the fetch.
 * @returns Parsed and validated `KitManifest`.
 *
 * @throws {Error} If the HTTP request fails (including 404 — assets not built).
 * @throws {Error} If the response JSON does not match the `KitManifest` shape.
 */
export async function loadKitManifest(id: string, signal?: AbortSignal): Promise<KitManifest> {
  const url = `/kits/${encodeURIComponent(id)}/manifest.json`;

  let response: Response;
  try {
    response = await fetch(url, { signal });
  } catch (err) {
    if (err instanceof DOMException && err.name === "AbortError") {
      throw err;
    }
    throw new Error(
      `loadKitManifest: network error fetching manifest for kit "${id}": ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }

  if (response.status === 404) {
    throw new Error(
      `loadKitManifest: manifest not found for kit "${id}" (HTTP 404).\n` +
        `Kit assets may not have been built yet. Run:\n` +
        `  node scripts/build-kits.mjs\n` +
        `from the packages/mpcsample directory to copy WAVs and generate manifests.`,
    );
  }

  if (!response.ok) {
    throw new Error(
      `loadKitManifest: HTTP ${response.status} ${response.statusText} ` +
        `fetching manifest for kit "${id}" at ${url}`,
    );
  }

  let parsed: unknown;
  try {
    parsed = await response.json();
  } catch (err) {
    throw new Error(
      `loadKitManifest: invalid JSON in manifest for kit "${id}": ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }

  if (!isKitManifest(parsed)) {
    throw new Error(
      `loadKitManifest: manifest for kit "${id}" does not match the expected ` +
        `KitManifest shape. Check that the manifest was generated by the ` +
        `current version of build-kits.mjs (run: node scripts/build-kits.mjs).`,
    );
  }

  return parsed;
}
